version: '3.8'

services:
  beckn-bap:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - BECKN_GATEWAY_URL=https://uki-gateway.becknprotocol.io
      - BAP_ID=farmer-app.openagri.network
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mock-bpp:
    build: ./backend
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
    command: ["node", "mock-bpp.js"]
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - beckn-bap
      - mock-bpp
    restart: unless-stopped
